### ISSUE TITLE
Bower doesn't pull the less/font files. 

### ISSUE THREAD

**Issue by verystrongjoe** [rdash/rdash-ui#6]
I tried pulling the rdash files using bower install. I confirmed there are less/fonts in the repository. But it wan't pulled by the bower.

**Comment by Ehesp** [comment]
I just updated the `bower.json` which should now pull the less (https://github.com/rdash/rdash-ui/commit/958c12d441eeb9f917d56641a035c7be82aea5c5)

The fonts are within the `dist/fonts` directory. Not sure why bower is actually including the folder when it is set to be ignored, will check that.

**Comment by verystrongjoe** [comment]
@Ehesp  Thanks! I close this issue.
